name: CI

on:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Install
        run: npm install

      - name: Test
        run: npm run lint

      - name: Test
        run: npm test

      - name: Coverage
        run: npm run coverage

      - name: Headless Tests
        run: npm run test:browsers:headless

      - name: Build
        run: npm run build
